# .github/workflows/kicad-drc.yml

name: KiCad DRC Check

on:
  pull_request:  # Trigger on pull requests to main only
    branches:
      - main  

jobs:
  drc_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install KiCad
        run: |
          sudo apt-get update
          sudo apt-get install -y kicad

      - name: Find and run DRC on all PCB files
        run: |
          find . -name "*.kicad_pcb" -print0 | while IFS= read -r -d '' file; do
            echo "Running DRC for $file"
            kicad-cli pcb drc "$file"
          done
