# .github/workflows/platformio-build.yml

name: PlatformIO Build

on:
  pull_request:  # Trigger on pull requests
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Find and Build PlatformIO Projects
        run: |
          # Find all directories that contain a platformio.ini file and build each one
          find . -name "platformio.ini" -execdir platformio run \;
